# Description:
#   start_point: start point of path
#   end_point: end point of path
#   sf_at: diag level where it becomes Safe Fault
#   lf_at: diag level where it becomes Latent Fault
#   spf_at: diag level where it becomes Single Point Fault
#
# Note:
# empty-value for sf_at, lf_at and spf_at is "none"
# default values are:
#   sf_at: "none"
#   lf_at: "warn"
#   spf_at: "error"
---
/**:
  ros__parameters:
    required_modules:
      test_sensing:
        /sensing/lidar/left/pointcloud_ex :
          /sensing/lidar/concatenated/pointcloud : { sf_at: "warn", lf_at: "none", spf_at: "none" }

        /sensing/lidar/right/pointcloud_ex :
          /sensing/lidar/concatenated/pointcloud : { sf_at: "none", lf_at: "warn", spf_at: "none" }

        /sensing/lidar/top/pointcloud_ex :
          /sensing/lidar/concatenated/pointcloud : { sf_at: "none", lf_at: "warn", spf_at: "none" }
